/// Cooker — recipe loading and consumption engine (protocol v2).
///
/// Loads recipe.toml definitions from filesystem or compiled-in defaults.
/// Provides recipe data to consumers (NL-Cooker, dispatch_cook, etc.)
pub mod nl;

use std::path::Path;

// ── Recipe types ──────────────────────────────────────────────────────────────

#[derive(Debug, serde::Deserialize)]
pub struct Recipe {
    pub recipe: Option<RecipeMeta>,
    pub passkey_sharing: Option<PasskeySharingDef>,
    #[serde(default)]
    pub steps: Vec<Step>,
}

#[derive(Debug, serde::Deserialize)]
pub struct RecipeMeta {
    #[serde(default)]
    pub id: Option<String>,
    #[serde(default)]
    pub display_name: Option<String>,
}

#[derive(Debug, serde::Deserialize)]
pub struct PasskeySharingDef {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub origins: Vec<String>,
}

#[derive(Debug, serde::Deserialize, serde::Serialize)]
pub struct Step {
    pub title: String,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub run: Option<String>,
    #[serde(default)]
    pub cwd: Option<String>,
    #[serde(default)]
    pub note: Option<String>,
    #[serde(default)]
    pub config_patches: Option<Vec<serde_json::Value>>,
    #[serde(default)]
    pub files: Option<Vec<serde_json::Value>>,
    #[serde(default)]
    pub restart: Option<bool>,
    #[serde(default)]
    pub env: Option<std::collections::HashMap<String, String>>,
    /// Which environment executes this step. Required in v2.
    /// Values: "safeclaw", "safeclaw.vault", "openclaw"
    #[serde(default = "default_step_target")]
    pub target: String,
}

fn default_step_target() -> String { "openclaw".to_string() }

// ── Recipe loading ────────────────────────────────────────────────────────────

/// Load a recipe by service ID. Checks filesystem first, falls back to compiled-in.
pub fn load_recipe(service_id: &str) -> Option<Recipe> {
    // Try filesystem paths
    let categories = ["system", "llm", "channel", "integration"];
    let base_dirs = discover_base_dirs();

    for base in &base_dirs {
        for cat in &categories {
            let path = base.join(cat).join(service_id).join("recipe.toml");
            if let Some(r) = try_load_recipe(&path) { return Some(r); }
        }
        let path = base.join(service_id).join("recipe.toml");
        if let Some(r) = try_load_recipe(&path) { return Some(r); }
    }

    // Compiled-in fallback (generated by build.rs)
    for (id, toml_str) in crate::generated_services::compiled_recipe_tomls() {
        if *id == service_id {
            return toml::from_str(toml_str).ok();
        }
    }

    None
}

/// List all available recipe IDs (from compiled-in registry).
pub fn available_recipes() -> Vec<&'static str> {
    crate::generated_services::compiled_recipe_tomls()
        .iter()
        .map(|(id, _)| *id)
        .collect()
}

fn try_load_recipe(path: &Path) -> Option<Recipe> {
    let content = std::fs::read_to_string(path).ok()?;
    toml::from_str(&content).ok()
}

fn discover_base_dirs() -> Vec<std::path::PathBuf> {
    let mut dirs = Vec::new();
    if let Ok(data) = std::env::var("SAFECLAW_DATA") {
        dirs.push(Path::new(&data).join("services"));
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
            dirs.push(parent.join("services"));
        }
    }
    // User-installed services (~/.safeclaw/services/)
    if let Some(user_dir) = crate::service::user_services_dir() {
        if user_dir.is_dir() {
            dirs.push(user_dir);
        }
    }
    dirs
}
