/// Build script: scan services/ directory and generate compiled-in TOML registries.
///
/// Generates src/generated_services.rs with:
///   - compiled_service_tomls() -> &[(&str, &str)]
///   - compiled_policy_tomls() -> &[(&str, &str)]
///   - compiled_provider_tomls() -> &[(&str, &str)]  (services/_providers/*.toml)
///
/// This eliminates hand-written include_str! lists — adding a new service
/// just requires creating a TOML file in services/.

use std::fs;
use std::path::Path;

fn main() {
    let services_dir = Path::new("services");
    let out_path = Path::new("src").join("generated_services.rs");

    let mut service_entries = Vec::new();
    let mut policy_entries = Vec::new();
    let mut provider_entries = Vec::new();

    // Scan services/{category}/{id}/ layout
    if services_dir.is_dir() {
        scan_services(services_dir, &mut service_entries, &mut policy_entries);
    }

    // Scan services/_providers/*.toml — shared [provider.<name>] templates.
    let providers_dir = services_dir.join("_providers");
    if providers_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&providers_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                    continue;
                }
                let name = path.file_stem().unwrap().to_str().unwrap().to_string();
                let rel = path.to_str().unwrap().to_string();
                provider_entries.push((name, rel));
            }
        }
    }

    // Sort for deterministic output
    service_entries.sort();
    policy_entries.sort();
    provider_entries.sort();

    // Generate Rust source
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    code.push_str("/// Compiled-in service.toml definitions. Tuple is\n");
    code.push_str("/// (id, category, toml_content) — `category` is derived from the\n");
    code.push_str("/// services/{category}/{id}/ directory (SSoT), not a toml field.\n");
    code.push_str("pub fn compiled_service_tomls() -> &'static [(&'static str, &'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, category, rel_path) in &service_entries {
        code.push_str(&format!(
            "        (\"{}\", \"{}\", include_str!(\"../{}\") ),\n",
            id, category, rel_path
        ));
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("/// Compiled-in policy.toml definitions.\n");
    code.push_str("pub fn compiled_policy_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &policy_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", id, rel_path));
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("/// Compiled-in provider TOML definitions (services/_providers/*.toml).\n");
    code.push_str("/// Tuple is (provider_file_stem, toml_content).\n");
    code.push_str("pub fn compiled_provider_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (name, rel_path) in &provider_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", name, rel_path));
    }
    code.push_str("    ]\n}\n");

    fs::write(&out_path, code).expect("Failed to write generated_services.rs");

    // Tell cargo to re-run if services/ changes
    println!("cargo:rerun-if-changed=services");
}

fn scan_services(
    base: &Path,
    // (id, category, rel_path). `category` comes from the services/{category}/{id}/
    // directory — the single source of truth (services no longer carry a
    // `[service] category` field).
    service_entries: &mut Vec<(String, String, String)>,
    policy_entries: &mut Vec<(String, String)>,
) {
    let Ok(categories) = fs::read_dir(base) else { return };

    for cat_entry in categories.flatten() {
        let cat_path = cat_entry.path();
        if !cat_path.is_dir() { continue; }
        // Skip underscore-prefixed dirs: `_providers` (handled separately) and
        // `_parked` (system-category / daemon-exec services excluded from v4).
        if cat_path.file_name().and_then(|n| n.to_str()).map_or(false, |n| n.starts_with('_')) {
            continue;
        }

        // Check if this is a direct service dir (flat layout) or a category dir
        let service_toml = cat_path.join("service.toml");
        if service_toml.exists() {
            // Flat: services/{id}/service.toml — no category dir, default it.
            let id = cat_path.file_name().unwrap().to_str().unwrap().to_string();
            let rel = service_toml.to_str().unwrap().to_string();
            service_entries.push((id.clone(), "integration".to_string(), rel));

            let policy_toml = cat_path.join("policy.toml");
            if policy_toml.exists() {
                policy_entries.push((id, policy_toml.to_str().unwrap().to_string()));
            }
            continue;
        }

        // Nested: services/{category}/{id}/ — the dir name IS the category.
        let category = cat_path.file_name().unwrap().to_str().unwrap().to_string();
        let Ok(svc_entries) = fs::read_dir(&cat_path) else { continue };
        for svc_entry in svc_entries.flatten() {
            let svc_path = svc_entry.path();
            if !svc_path.is_dir() { continue; }

            let id = svc_path.file_name().unwrap().to_str().unwrap().to_string();

            let st = svc_path.join("service.toml");
            if st.exists() {
                service_entries.push((id.clone(), category.clone(), st.to_str().unwrap().to_string()));
            }

            let pt = svc_path.join("policy.toml");
            if pt.exists() {
                policy_entries.push((id, pt.to_str().unwrap().to_string()));
            }
        }
    }
}
