/// Build script: scan services/ directory and generate compiled-in TOML registries.
///
/// Generates src/generated_services.rs with:
///   - compiled_service_tomls() -> &[(&str, &str)]
///   - compiled_recipe_tomls() -> &[(&str, &str)]
///   - compiled_policy_tomls() -> &[(&str, &str)]
///
/// This eliminates hand-written include_str! lists — adding a new service
/// just requires creating a TOML file in services/.

use std::fs;
use std::path::Path;

fn main() {
    let services_dir = Path::new("services");
    let out_path = Path::new("src").join("generated_services.rs");

    let mut service_entries = Vec::new();
    let mut recipe_entries = Vec::new();
    let mut policy_entries = Vec::new();

    // Scan services/{category}/{id}/ layout
    if services_dir.is_dir() {
        scan_services(services_dir, &mut service_entries, &mut recipe_entries, &mut policy_entries);
    }

    // Sort for deterministic output
    service_entries.sort();
    recipe_entries.sort();
    policy_entries.sort();

    // Generate Rust source
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    code.push_str("/// Compiled-in service.toml definitions.\n");
    code.push_str("pub fn compiled_service_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &service_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", id, rel_path));
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("/// Compiled-in recipe.toml definitions.\n");
    code.push_str("pub fn compiled_recipe_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &recipe_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", id, rel_path));
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("/// Compiled-in policy.toml definitions.\n");
    code.push_str("pub fn compiled_policy_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &policy_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", id, rel_path));
    }
    code.push_str("    ]\n}\n");

    fs::write(&out_path, code).expect("Failed to write generated_services.rs");

    // Tell cargo to re-run if services/ changes
    println!("cargo:rerun-if-changed=services");
}

fn scan_services(
    base: &Path,
    service_entries: &mut Vec<(String, String)>,
    recipe_entries: &mut Vec<(String, String)>,
    policy_entries: &mut Vec<(String, String)>,
) {
    let Ok(categories) = fs::read_dir(base) else { return };

    for cat_entry in categories.flatten() {
        let cat_path = cat_entry.path();
        if !cat_path.is_dir() { continue; }

        // Check if this is a direct service dir (flat layout) or a category dir
        let service_toml = cat_path.join("service.toml");
        if service_toml.exists() {
            // Flat: services/{id}/service.toml
            let id = cat_path.file_name().unwrap().to_str().unwrap().to_string();
            let rel = service_toml.to_str().unwrap().to_string();
            service_entries.push((id.clone(), rel));

            let recipe_toml = cat_path.join("recipe.toml");
            if recipe_toml.exists() {
                recipe_entries.push((id.clone(), recipe_toml.to_str().unwrap().to_string()));
            }

            let policy_toml = cat_path.join("policy.toml");
            if policy_toml.exists() {
                policy_entries.push((id, policy_toml.to_str().unwrap().to_string()));
            }
            continue;
        }

        // Nested: services/{category}/{id}/
        let Ok(svc_entries) = fs::read_dir(&cat_path) else { continue };
        for svc_entry in svc_entries.flatten() {
            let svc_path = svc_entry.path();
            if !svc_path.is_dir() { continue; }

            let id = svc_path.file_name().unwrap().to_str().unwrap().to_string();

            let st = svc_path.join("service.toml");
            if st.exists() {
                service_entries.push((id.clone(), st.to_str().unwrap().to_string()));
            }

            let rt = svc_path.join("recipe.toml");
            if rt.exists() {
                recipe_entries.push((id.clone(), rt.to_str().unwrap().to_string()));
            }

            let pt = svc_path.join("policy.toml");
            if pt.exists() {
                policy_entries.push((id, pt.to_str().unwrap().to_string()));
            }
        }
    }
}
