/// Build script: scan services/ directory and generate compiled-in TOML registries.
///
/// Generates src/generated_services.rs with:
///   - compiled_service_tomls() -> &[(&str, &str)]
///   - compiled_policy_tomls() -> &[(&str, &str)]
///
/// This eliminates hand-written include_str! lists — adding a new service
/// just requires creating a TOML file in services/.

use std::fs;
use std::path::Path;

fn main() {
    let services_dir = Path::new("services");
    let out_path = Path::new("src").join("generated_services.rs");

    let mut service_entries = Vec::new();
    let mut policy_entries = Vec::new();

    // Scan the flat services/{id}/ layout. The directory name IS the service
    // id — flat so the filesystem itself enforces id uniqueness. Grouping /
    // classification is data, not layout: the `[service] tags` toml field.
    if services_dir.is_dir() {
        scan_services(services_dir, &mut service_entries, &mut policy_entries);
    }

    // Sort for deterministic output
    service_entries.sort();
    policy_entries.sort();

    // Generate Rust source
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    code.push_str("/// Compiled-in service.toml definitions. Tuple is (id, toml_content);\n");
    code.push_str("/// id = the services/{id}/ directory name.\n");
    code.push_str("pub fn compiled_service_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &service_entries {
        code.push_str(&format!(
            "        (\"{}\", include_str!(\"../{}\") ),\n",
            id, rel_path
        ));
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("/// Compiled-in policy.toml definitions.\n");
    code.push_str("pub fn compiled_policy_tomls() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (id, rel_path) in &policy_entries {
        code.push_str(&format!("        (\"{}\", include_str!(\"../{}\") ),\n", id, rel_path));
    }
    code.push_str("    ]\n}\n");

    fs::write(&out_path, code).expect("Failed to write generated_services.rs");

    // Tell cargo to re-run if services/ changes
    println!("cargo:rerun-if-changed=services");
}

fn scan_services(
    base: &Path,
    // (id, rel_path) — flat services/{id}/service.toml only.
    service_entries: &mut Vec<(String, String)>,
    policy_entries: &mut Vec<(String, String)>,
) {
    let Ok(entries) = fs::read_dir(base) else { return };

    for entry in entries.flatten() {
        let svc_path = entry.path();
        if !svc_path.is_dir() { continue; }
        // Skip underscore-prefixed dirs, e.g. `_parked` (services excluded
        // from the build).
        if svc_path.file_name().and_then(|n| n.to_str()).map_or(false, |n| n.starts_with('_')) {
            continue;
        }

        let id = svc_path.file_name().unwrap().to_str().unwrap().to_string();

        let st = svc_path.join("service.toml");
        if st.exists() {
            service_entries.push((id.clone(), st.to_str().unwrap().to_string()));
        }

        let pt = svc_path.join("policy.toml");
        if pt.exists() {
            policy_entries.push((id, pt.to_str().unwrap().to_string()));
        }
    }
}
