[service]
id = "gcalendar"
name = "Google Calendar"
sub = "Google"
category = "integration"

[[upstream]]
id = "default"
url = "https://www.googleapis.com/calendar/v3"

[upstream.auth]
provider = "google"
scopes = [
  "https://www.googleapis.com/auth/calendar.events",
]
secret = "gcalendar_refresh_token"

[upstream.headers]
Authorization = "Bearer {{oauth.access_token}}"

[[api]]
path = "*"

  [[api.steps]]
  target = "upstream:default"
  returns = true
