[service]
id = "gdrive"
name = "Google Drive"
sub = "Google"
category = "integration"

[[upstream]]
id = "default"
url = "https://www.googleapis.com/drive/v3"
auth = { type = "oauth2", provider = "google" }

[[api]]
path = "*"

  [[api.steps]]
  target = "upstream:default"
  returns = true
