[service]
id = "gmail"
name = "Gmail"
sub = "Google"
category = "integration"

[[upstream]]
id = "default"
url = "https://gmail.googleapis.com"

[upstream.auth]
provider = "google"
scopes = [
  "https://www.googleapis.com/auth/gmail.send",
  "https://www.googleapis.com/auth/gmail.readonly",
  "https://www.googleapis.com/auth/gmail.modify",
]
secret = "GMAIL_REFRESH_TOKEN"

[upstream.headers]
Authorization = "Bearer {{oauth.access_token}}"

[[api]]
path = "*"

  [[api.steps]]
  target = "upstream:default"
  returns = true
