[service]
id = "gmail"
name = "Gmail"

hosts = ["gmail.googleapis.com"]

[oauth2]
provider = "google"
scopes = [
  "https://www.googleapis.com/auth/gmail.send",
  "https://www.googleapis.com/auth/gmail.readonly",
  "https://www.googleapis.com/auth/gmail.modify",
]
secret = "GMAIL_REFRESH_TOKEN"
