//! `sc start` / `stop` / `restart` / `logs` — user-level systemd lifecycle.
//!
//! These commands install a per-user systemd unit at
//! `~/.config/systemd/user/safeclaw.service` and drive it via
//! `systemctl --user`. Linux only.
//!
//! Why user-level (not system-level)?
//! - No sudo required — the daemon runs as the same user that called `sc start`.
//! - Vault state lives under `$HOME/.safeclaw/`, owned by the same user.
//! - Encapsulates "this user's SafeClaw daemon" cleanly. Multi-user hosts
//!   work too, each user gets their own daemon.
//!
//! Operators running SafeClaw as a system service (root-owned, the dev VM
//! shape) should write their own `/etc/systemd/system/safeclaw.service`
//! and not touch these commands.

use std::process::Command as ProcCommand;
use crate::config::LogsArgs;

const UNIT_BASENAME: &str = "safeclaw.service";
/// First line of every unit we generate. The idempotency guard refuses to
/// overwrite a unit that lacks this marker (a hand-written one) unless
/// `--force` is passed.
const UNIT_MARKER: &str = "# Generated by safeclaw — do not edit; re-run `sc up` to refresh.";
/// Stable substring used for *detection* (the "is this our unit?" guard).
/// The full `UNIT_MARKER`'s trailing hint has drifted across versions
/// (`sc custodian start` → `sc up`), so detecting on the whole string
/// orphaned units written by older builds — `sc` stopped recognizing its
/// own unit and refused to manage it. Detect on this invariant prefix; all
/// safeclaw-generated units (past and present) start the marker line with it.
const UNIT_MARKER_DETECT: &str = "# Generated by safeclaw";

#[cfg(target_os = "linux")]
pub async fn run_start_systemd(force: bool) -> Result<(), String> {
    let bin = std::env::current_exe()
        .map_err(|e| format!("can't find current binary path: {}", e))?;
    let bin_str = bin.to_string_lossy().to_string();

    // Collect any SAFECLAW_* env vars set in the calling shell — these
    // become Environment= lines in the unit. The user controls config
    // by setting env vars *before* `sc start`; flags are ignored here
    // (they'd be invisible after install, which is worse).
    let mut env_lines = Vec::new();
    for (k, v) in std::env::vars() {
        // Don't leak the agent-facing SAFECLAW_API_KEY into the daemon's
        // env — the daemon reads its api-key from the FILE `~/.safeclaw/api-key`
        // (provisioned below), and a stray/foreign value in the operator's
        // shell must not be adopted as the broker key.
        if k.starts_with("SAFECLAW_") && k != "SAFECLAW_API_KEY" {
            // systemd unit syntax: quote the value to allow spaces/=.
            // Escape any " inside.
            let v_escaped = v.replace('"', "\\\"");
            env_lines.push(format!("Environment=\"{}={}\"", k, v_escaped));
        }
    }
    // Broker auth is the cloud-synced agent-key hash-set (agent ≡ api-key),
    // refreshed at runtime by `crate::sync` — there's no machine-local key file
    // to provision here. See [[project_vault_agent_architecture_2026_06_25]].
    let env_block = if env_lines.is_empty() { String::new() } else { format!("{}\n", env_lines.join("\n")) };

    let unit = format!(
        "{UNIT_MARKER}\n\
         [Unit]\n\
         Description=SafeClaw daemon (user)\n\
         After=network.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         {env_block}\
         ExecStart={bin} serve\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        env_block = env_block,
        bin = bin_str,
    );

    let unit_dir = dirs::config_dir()
        .ok_or("can't locate user config dir (XDG_CONFIG_HOME)")?
        .join("systemd/user");
    std::fs::create_dir_all(&unit_dir)
        .map_err(|e| format!("create {}: {}", unit_dir.display(), e))?;
    let unit_path = unit_dir.join(UNIT_BASENAME);
    // Idempotency guard: never silently clobber a unit we didn't generate.
    // A unit lacking the (version-stable) safeclaw marker prefix is
    // hand-written; refuse unless --force. We match `UNIT_MARKER_DETECT`
    // (not the full `UNIT_MARKER`) so units written by older builds — whose
    // marker tail differs — are still recognized as ours.
    if !force {
        if let Ok(existing) = std::fs::read_to_string(&unit_path) {
            if !existing.contains(UNIT_MARKER_DETECT) {
                return Err(format!(
                    "{} already exists and was not generated by safeclaw \
                     (no marker). Refusing to overwrite. Re-run with `--force` \
                     to replace it, or `sc up` to just start the existing unit.",
                    unit_path.display()
                ));
            }
        }
    }
    std::fs::write(&unit_path, &unit)
        .map_err(|e| format!("write {}: {}", unit_path.display(), e))?;
    // Unit may embed SAFECLAW_ADMIN_KEY and other secrets via
    // Environment= lines. Tighten to user-only so other accounts on a
    // multi-user host can't read them.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&unit_path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("chmod 0600 {}: {}", unit_path.display(), e))?;
    }

    run_systemctl(&["daemon-reload"], "daemon-reload")?;
    run_systemctl(&["enable", "--now", UNIT_BASENAME], "enable+start")?;

    eprintln!("✓ daemon enabled and running ({})", unit_path.display());
    eprintln!("  binary:   {}", bin_str);
    if !env_lines.is_empty() {
        eprintln!("  env:      {} SAFECLAW_* var(s) embedded", env_lines.len());
    }
    eprintln!("  broker:   requires an agent key (synced from your account); mint one with `sc agent add` or the dashboard's \"Connect a new agent\"");
    eprintln!();
    eprintln!("  next: `sc login --pair-token <token>` to connect this daemon to your vault (token from the dashboard)");
    eprintln!("        `sc logs -f` to tail, `sc down` to stop, `sc restart` to reload");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub async fn run_start_systemd(_force: bool) -> Result<(), String> {
    Err("`sc up` (systemd mode) is Linux-only. Use `sc serve` to run in this process.".into())
}

/// Idempotent "ensure the daemon is running" — the skill's lazy-start target.
/// Starts the user-level unit only if it isn't already active; never rewrites
/// the unit (so it can't clobber config or race a concurrent start). If no
/// unit is installed yet, it tells the user to run `sc up` once.
#[cfg(target_os = "linux")]
pub fn run_ensure_running() -> Result<(), String> {
    // Already active? Nothing to do — this is the common case the skill hits
    // every session, so keep it cheap and silent-ish.
    let active = ProcCommand::new("systemctl")
        .args(["--user", "is-active", "--quiet", UNIT_BASENAME])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if active {
        return Ok(());
    }
    // Not active. If the unit exists, just start it (no rewrite). Otherwise
    // the daemon was never installed as a service — guide the user.
    ensure_unit_installed().map_err(|_| {
        "daemon is not running and no service is installed — run `sc up` once to install it".to_string()
    })?;
    run_systemctl(&["start", UNIT_BASENAME], "start")?;
    eprintln!("✓ daemon started");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_ensure_running() -> Result<(), String> {
    Err("`sc up` (systemd mode) is Linux-only. Use `sc serve` to run in this process.".into())
}

#[cfg(target_os = "linux")]
pub fn run_stop() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["stop", UNIT_BASENAME], "stop")?;
    eprintln!("✓ daemon stopped");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_stop() -> Result<(), String> {
    Err("`sc down` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_restart() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["restart", UNIT_BASENAME], "restart")?;
    eprintln!("✓ daemon restarted");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_restart() -> Result<(), String> {
    Err("`sc restart` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_logs(args: LogsArgs) -> Result<(), String> {
    ensure_unit_installed()?;
    let n = args.lines.to_string();
    let mut cmd = ProcCommand::new("journalctl");
    cmd.args(["--user", "-u", UNIT_BASENAME, "-n", &n]);
    // `-o cat` prints only the daemon's own log line — which already carries an
    // ISO timestamp + level + module — dropping journald's redundant
    // `<date> <host> sc[pid]:` prefix that otherwise doubles the timestamp and
    // pushes the useful message off the right edge. `--raw` restores the full
    // journald format (local wall-clock, host, pid) when you want it.
    if !args.raw {
        cmd.args(["-o", "cat"]);
    }
    if args.follow {
        cmd.arg("-f");
    }
    // Inherit stdio so journalctl prints directly + Ctrl-C works.
    let status = cmd.status()
        .map_err(|e| format!("spawn journalctl: {}", e))?;
    if !status.success() {
        return Err(format!("journalctl exited with status {}", status));
    }
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_logs(_args: LogsArgs) -> Result<(), String> {
    Err("`sc logs` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
fn ensure_unit_installed() -> Result<(), String> {
    let unit_path = dirs::config_dir()
        .ok_or("can't locate user config dir")?
        .join("systemd/user")
        .join(UNIT_BASENAME);
    if !unit_path.exists() {
        return Err(format!(
            "no systemd unit at {} — run `sc up` first to install it",
            unit_path.display()
        ));
    }
    Ok(())
}

/// True if the user-level systemd unit is already installed. Lets `sc up`
/// decide between first-time install (`run_start_systemd`) and the light
/// everyday ensure-running. False on non-Linux (no systemd unit concept).
pub fn unit_installed() -> bool {
    #[cfg(target_os = "linux")]
    {
        dirs::config_dir()
            .map(|d| d.join("systemd/user").join(UNIT_BASENAME).exists())
            .unwrap_or(false)
    }
    #[cfg(not(target_os = "linux"))]
    {
        false
    }
}

/// Migrate a stale unit whose ExecStart still calls the removed `custodian run`
/// subcommand to the new `serve` entrypoint, in place (preserving the embedded
/// env block), then daemon-reload. Returns Ok(true) if it rewrote anything;
/// no-op when the unit is missing or already current. Called by `sc up` and
/// `sc upgrade` BEFORE they (re)start the daemon, so removing `custodian`
/// doesn't break a unit installed by an older build.
#[cfg(target_os = "linux")]
pub fn reconcile_unit_execstart() -> Result<bool, String> {
    let unit_path = dirs::config_dir()
        .ok_or("can't locate user config dir")?
        .join("systemd/user")
        .join(UNIT_BASENAME);
    let Ok(contents) = std::fs::read_to_string(&unit_path) else {
        return Ok(false);
    };
    if !contents.contains(" custodian run") {
        return Ok(false);
    }
    let fixed = contents.replace(" custodian run", " serve");
    std::fs::write(&unit_path, &fixed)
        .map_err(|e| format!("rewrite unit {}: {}", unit_path.display(), e))?;
    let _ = run_systemctl(&["daemon-reload"], "daemon-reload");
    Ok(true)
}

#[cfg(not(target_os = "linux"))]
pub fn reconcile_unit_execstart() -> Result<bool, String> {
    Ok(false)
}

#[cfg(target_os = "linux")]
fn run_systemctl(args: &[&str], action: &str) -> Result<(), String> {
    let mut cmd = ProcCommand::new("systemctl");
    cmd.arg("--user");
    cmd.args(args);
    let output = cmd.output()
        .map_err(|e| format!("spawn systemctl: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("systemctl --user {} failed: {}", action, stderr.trim()));
    }
    Ok(())
}
