//! `sc start` / `stop` / `restart` / `logs` — user-level systemd lifecycle.
//!
//! These commands install a per-user systemd unit at
//! `~/.config/systemd/user/safeclaw.service` and drive it via
//! `systemctl --user`. Linux only.
//!
//! Why user-level (not system-level)?
//! - No sudo required — the daemon runs as the same user that called `sc start`.
//! - Vault state lives under `$HOME/.safeclaw/`, owned by the same user.
//! - Encapsulates "this user's SafeClaw daemon" cleanly. Multi-user hosts
//!   work too, each user gets their own daemon.
//!
//! Operators running SafeClaw as a system service (root-owned, the dev VM
//! shape) should write their own `/etc/systemd/system/safeclaw.service`
//! and not touch these commands.

use std::process::Command as ProcCommand;
use crate::config::LogsArgs;

const UNIT_BASENAME: &str = "safeclaw.service";
/// First line of every unit we generate. The idempotency guard refuses to
/// overwrite a unit that lacks this marker (a hand-written one) unless
/// `--force` is passed.
const UNIT_MARKER: &str = "# Generated by safeclaw — do not edit; re-run `sc custodian start` to refresh.";

#[cfg(target_os = "linux")]
pub async fn run_start_systemd(force: bool) -> Result<(), String> {
    let bin = std::env::current_exe()
        .map_err(|e| format!("can't find current binary path: {}", e))?;
    let bin_str = bin.to_string_lossy().to_string();

    // Collect any SAFECLAW_* env vars set in the calling shell — these
    // become Environment= lines in the unit. The user controls config
    // by setting env vars *before* `sc start`; flags are ignored here
    // (they'd be invisible after install, which is worse).
    let mut env_lines = Vec::new();
    for (k, v) in std::env::vars() {
        // SAFECLAW_LOCAL_BEARER is provisioned below; skip any inherited
        // copy so it isn't emitted twice.
        if k.starts_with("SAFECLAW_") && k != "SAFECLAW_LOCAL_BEARER" {
            // systemd unit syntax: quote the value to allow spaces/=.
            // Escape any " inside.
            let v_escaped = v.replace('"', "\\\"");
            env_lines.push(format!("Environment=\"{}={}\"", k, v_escaped));
        }
    }
    // Provision (or reuse) the machine-local bearer token and embed it, so the
    // daemon enforces it on the broker plane. The same token is printed to the
    // agent by `sc install` as SAFECLAW_API_KEY.
    let bearer = crate::local_bearer::ensure_token()?;
    env_lines.push(format!("Environment=\"SAFECLAW_LOCAL_BEARER={}\"", bearer));
    let env_block = if env_lines.is_empty() { String::new() } else { format!("{}\n", env_lines.join("\n")) };

    let unit = format!(
        "{UNIT_MARKER}\n\
         [Unit]\n\
         Description=SafeClaw daemon (user)\n\
         After=network.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         {env_block}\
         ExecStart={bin} custodian run\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        env_block = env_block,
        bin = bin_str,
    );

    let unit_dir = dirs::config_dir()
        .ok_or("can't locate user config dir (XDG_CONFIG_HOME)")?
        .join("systemd/user");
    std::fs::create_dir_all(&unit_dir)
        .map_err(|e| format!("create {}: {}", unit_dir.display(), e))?;
    let unit_path = unit_dir.join(UNIT_BASENAME);
    // Idempotency guard: never silently clobber a unit we didn't generate.
    // A unit lacking UNIT_MARKER is hand-written (or pre-marker legacy);
    // refuse unless --force.
    if !force {
        if let Ok(existing) = std::fs::read_to_string(&unit_path) {
            if !existing.contains(UNIT_MARKER) {
                return Err(format!(
                    "{} already exists and was not generated by safeclaw \
                     (no marker). Refusing to overwrite. Re-run with `--force` \
                     to replace it, or `sc custodian ensure-running` to just \
                     start the existing unit.",
                    unit_path.display()
                ));
            }
        }
    }
    std::fs::write(&unit_path, &unit)
        .map_err(|e| format!("write {}: {}", unit_path.display(), e))?;
    // Unit may embed SAFECLAW_ADMIN_KEY and other secrets via
    // Environment= lines. Tighten to user-only so other accounts on a
    // multi-user host can't read them.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&unit_path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("chmod 0600 {}: {}", unit_path.display(), e))?;
    }

    run_systemctl(&["daemon-reload"], "daemon-reload")?;
    run_systemctl(&["enable", "--now", UNIT_BASENAME], "enable+start")?;

    eprintln!("✓ daemon enabled and running ({})", unit_path.display());
    eprintln!("  binary:   {}", bin_str);
    if !env_lines.is_empty() {
        eprintln!("  env:      {} SAFECLAW_* var(s) embedded (incl. local bearer)", env_lines.len());
    }
    eprintln!("  bearer:   broker plane now requires the token; agents get it via `sc install`");
    eprintln!();
    eprintln!("  next: `safeclaw vault create` to make your first vault");
    eprintln!("        `safeclaw install` to print the agent setup prompt (incl. the bearer)");
    eprintln!("        `safeclaw c logs -f` to tail, `safeclaw c stop` to stop, `safeclaw c restart` to reload");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub async fn run_start_systemd(_force: bool) -> Result<(), String> {
    Err("`sc c start` (systemd mode) is Linux-only. Use `sc c run` to run in this process.".into())
}

/// Idempotent "ensure the daemon is running" — the skill's lazy-start target.
/// Starts the user-level unit only if it isn't already active; never rewrites
/// the unit (so it can't clobber config or race a concurrent start). If no
/// unit is installed yet, it tells the user to run `sc custodian start` once.
#[cfg(target_os = "linux")]
pub fn run_ensure_running() -> Result<(), String> {
    // Already active? Nothing to do — this is the common case the skill hits
    // every session, so keep it cheap and silent-ish.
    let active = ProcCommand::new("systemctl")
        .args(["--user", "is-active", "--quiet", UNIT_BASENAME])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if active {
        return Ok(());
    }
    // Not active. If the unit exists, just start it (no rewrite). Otherwise
    // the daemon was never installed as a service — guide the user.
    ensure_unit_installed().map_err(|_| {
        "daemon is not running and no service is installed — run `sc custodian start` once to install it".to_string()
    })?;
    run_systemctl(&["start", UNIT_BASENAME], "start")?;
    eprintln!("✓ daemon started");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_ensure_running() -> Result<(), String> {
    Err("`sc c ensure-running` (systemd mode) is Linux-only. Use `sc c run` to run in this process.".into())
}

#[cfg(target_os = "linux")]
pub fn run_stop() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["stop", UNIT_BASENAME], "stop")?;
    eprintln!("✓ daemon stopped");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_stop() -> Result<(), String> {
    Err("`sc c stop` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_restart() -> Result<(), String> {
    ensure_unit_installed()?;
    run_systemctl(&["restart", UNIT_BASENAME], "restart")?;
    eprintln!("✓ daemon restarted");
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_restart() -> Result<(), String> {
    Err("`sc c restart` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
pub fn run_logs(args: LogsArgs) -> Result<(), String> {
    ensure_unit_installed()?;
    let n = args.lines.to_string();
    let mut cmd = ProcCommand::new("journalctl");
    cmd.args(["--user", "-u", UNIT_BASENAME, "-n", &n]);
    if args.follow {
        cmd.arg("-f");
    }
    // Inherit stdio so journalctl prints directly + Ctrl-C works.
    let status = cmd.status()
        .map_err(|e| format!("spawn journalctl: {}", e))?;
    if !status.success() {
        return Err(format!("journalctl exited with status {}", status));
    }
    Ok(())
}

#[cfg(not(target_os = "linux"))]
pub fn run_logs(_args: LogsArgs) -> Result<(), String> {
    Err("`sc c logs` (systemd mode) is Linux-only.".into())
}

#[cfg(target_os = "linux")]
fn ensure_unit_installed() -> Result<(), String> {
    let unit_path = dirs::config_dir()
        .ok_or("can't locate user config dir")?
        .join("systemd/user")
        .join(UNIT_BASENAME);
    if !unit_path.exists() {
        return Err(format!(
            "no systemd unit at {} — run `sc c start` first to install it",
            unit_path.display()
        ));
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn run_systemctl(args: &[&str], action: &str) -> Result<(), String> {
    let mut cmd = ProcCommand::new("systemctl");
    cmd.arg("--user");
    cmd.args(args);
    let output = cmd.output()
        .map_err(|e| format!("spawn systemctl: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("systemctl --user {} failed: {}", action, stderr.trim()));
    }
    Ok(())
}
